dist: bionic
language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
#
before_install:
    - sudo apt-get -y update
    - sudo apt-get -y install libudunits2-0
    - sudo apt-get -y install libudunits2-dev
    - sudo apt-get -y install libnetcdf-dev 
    - sudo apt-get -y install libnetcdf-dev 
    - sudo apt-get -y install libnetcdff-dev
    - sudo apt-get -y install libhdf5-dev
      #    - sudo apt-get -y install cdo
    - sudo apt-get -y install nco
#
#
#addons:
#    apt:
#        update: true
#cach:
#    apt: true
#
install:

    - wget https://code.mpimet.mpg.de/attachments/download/20826/cdo-1.9.8.tar.gz 
    - tar -xvzf cdo-1.9.8.tar.gz
    - cd cdo-1.9.8
    - ./configure
    - sudo make && make check && make install

    - python setup.py install
# command to run tests
script:
  - which cdo
  - cdo --version 
  - pytest
