dist: bionic
language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
#
before_install:
    - sudo apt-get -y update
    - sudo apt-get -y install libudunits2-0
    - sudo apt-get -y install libudunits2-dev
    - sudo apt-get -y install libnetcdf-dev 
    - sudo apt-get -y install libnetcdf-dev 
    - sudo apt-get -y install libnetcdff-dev
    - sudo apt-get -y install libhdf5-dev
      #    - sudo apt-get -y install cdo
    - sudo apt-get -y install nco
#
#
#addons:
#    apt:
#        update: true
#cach:
#    apt: true
#
install:

    - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4/hdf5-1.8.13.tar.gz
    - tar -xvf hdf5-1.8.13.tar.gz
    - cd hdf5-1.8.13/
    - ./configure -with-zlib=/opt/cdo-install -prefix=/opt/cdo-install CFLAGS=-fPIC

    - sudo make 
    - sudo make check
    - sudo make install
    - cd ..

    - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.0.tar.gz
    - tar -xvf netcdf-4.4.0.tar.gz 
    - cd netcdf-4.4.0/ 
    - CPPFLAGS=-I/opt/cdo-install/include LDFLAGS=-L/opt/cdo-install/lib ./configure -prefix=/opt/cdo-install CFLAGS=-fPIC 
    - sudo make 
    - sudo make check
    - sudo make install

    - cd ..




    - wget https://code.mpimet.mpg.de/attachments/download/20826/cdo-1.9.8.tar.gz 
    - tar -xvzf cdo-1.9.8.tar.gz
    - cd cdo-1.9.8
    - ./configure -with-netcdf=/opt/cdo-install -with-hdf5=/opt/cdo-install 
 
    - sudo make 
    - sudo make install
    - cd ..

    - python setup.py install
# command to run tests
script:
  - which cdo
  - cdo --version 
  - cdo showyear data/sst.mon.mean.nc
    #- pytest
