language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
#
before_install:
    - sudo apt-get update
    - sudo apt-get -y install cdo
    - sudo apt-get -y install nco
install:
- python setup.py install
# command to run tests
script:
  - pytest
