dist: xenial
language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
#
before_install:
    - sudo apt update
    - sudo apt install cdo
    - sudo apt install nco

#addons:
#    packages:
#        nco
#        cdo: "1.9.8"
install:
- python setup.py install
# command to run tests
script:
  - which cdo
  - cdo --version 
  - which cdo-bin 
    #- pytest
