
os:
  - linux


language: python
python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"      # current default Python on Travis CI
    - "3.8"      # current default Python on Travis CI


install:


  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    #- conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - conda activate test-environment
  - conda install -c conda-forge eccodes=2.18.0
  - conda install -c conda-forge cdo
  - conda install -c conda-forge nco
  - conda install -c anaconda coverage
  - conda install -c anaconda pytest
 
  - pip install numpy
  - pip install -r requirements.txt
  - pip install pandas 
  - python setup.py install
#
script:
    - coverage run -m pytest tests/test*.py


after_success:
    - bash <(curl -s https://codecov.io/bash)

