language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
#
addons:
    packages:
        nco
        cdo: "1.9.8"
install:
- python setup.py install
# command to run tests
script:
  - which cdo
  - cdo --version 
  - which cdo-bin 
    #- pytest
