
# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create -n myenv python=3.6
            source activate myenv
            conda install cdo
            conda install pytest
            conda install nco
            conda install xarray

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            source activate myenv
            pytest -v --cov


