# Python CircleCI 2.0 configuration file
version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create -n nctoolkit python=3.9 -y
            conda install -c conda-forge gcc=12.1.0


      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            #conda init bash

            eval "$(conda shell.bash hook)"
            conda activate nctoolkit
            conda install -c conda-forge cdo=1.9.10 nco -y
            pip install pytest
            pip install coverage
            pip install rioxarray
            pip install --user codecov
            pip install .
            coverage run -m pytest tests/test_*.py
            coverage report
            coverage xml
      - store_artifacts:
          path: xmlcov
      
      - codecov/upload:
          file: coverage.xml
