# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux testing 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: "ubuntu-latest" 

    steps:

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-name: foo
          create-args: cdo nco geos
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
      - name: Run python testing
        run: 
          mamba activate foo
          pip install xarray
          pip install rioxarray
          pip install pytest
          pip install numpy 
          pip install cartopy
          pip install dask
          pip install -r requirements.txt
          pip install .
          pip install pandas
          pip install rioxarray
          pip install pytest
          pip install pytest-cov
          pip install coverage 
          pytest tests/test*.py
        #shell: micromamba-shell {0}
        shell: bash -l {0} 